language: cpp

sudo: false

# build matrix #

matrix:
  include:
  # linux/gcc
  - os: linux
    compiler: gcc
    env: compiler=g++-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - libzmq3-dev
        - g++-4.9
        - ninja-build
        
  # linux/clang
  - os: linux
    compiler: clang
    addons:
      apt:
        packages:
        - cmake
        - libzmq3-dev

# build script #
before_install:
  - ./configure.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make


